chemicals:
  benzene:
    cas: 71-43-2
    pubchem_cid: 241
    iupac_name: benzene
    molecular_formula: C6H6
    molecular_weight_g_per_mol: 78.11
    hts_codes:
    - 2902.20.00
    status: feedstock_only
  nitrobenzene:
    cas: 100-00-5
    pubchem_cid: 7474
    iupac_name: 1-chloro-4-nitrobenzene
    molecular_formula: C6H4ClNO2
    molecular_weight_g_per_mol: 157.55
    hts_codes:
    - 2904.20.10
    status: feedstock_only
  aniline:
    cas: 62-53-3
    pubchem_cid: 6115
    iupac_name: aniline
    molecular_formula: C6H7N
    molecular_weight_g_per_mol: 93.13
    hts_codes:
    - 2921.41.20
    status: active
